# Generated by Django 5.2.3 on 2025-06-21 00:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_category_slug"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
