# Generated by Django 5.2.3 on 2025-06-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_delete_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="page_type",
            field=models.CharField(
                choices=[
                    ("post", "Regular Post"),
                    ("featured", "Featured Post"),
                    ("navbar", "Navigation Bar Post"),
                ],
                default="post",
                max_length=20,
            ),
        ),
    ]
